name: Gunluk Finansal Veri Cekimi

on:
  schedule:
    - cron: '0 18 * * 1-5'
  workflow_dispatch:

jobs:
  veri-guncelle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Gereksinimleri Yukle
        run: pip install -r requirements.txt
      - name: Python Scriptini Calistir
        run: python veri_cek.py
      - name: CSV Dosyalarini Repoya Kaydet
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add *.csv
          git commit -m "CSV verileri guncellendi" || echo "Degisiklik yok"
          git push
